export default {
	// GITHUB PROFILES
	REQUESTED_ALL_GITHUB_PROFILES: "REQUESTED_ALL_GITHUB_PROFILES",
	SUCCEEDED_ALL_GITHUB_PROFILES: "SUCCEEDED_ALL_GITHUB_PROFILES",
	FAILED_ALL_GITHUB_PROFILES: "FAILED_ALL_GITHUB_PROFILES",
	REQUESTED_FAVORITE_GITHUB_PROFILES: "REQUESTED_FAVORITE_GITHUB_PROFILES",
	SUCCEEDED_FAVORITE_GITHUB_PROFILES: "SUCCEEDED_FAVORITE_GITHUB_PROFILES",
	FAILED_FAVORITE_GITHUB_PROFILES: "FAILED_FAVORITE_GITHUB_PROFILES",
	// LINKEDIN PROFILES
	REQUESTED_ALL_FAVORITE_LINKEDIN_PROFILES:"REQUESTED_ALL_FAVORITE_LINKEDIN_PROFILES",
	FAILED_ALL_FAVORITE_LINKEDIN_PROFILES:"FAILED_ALL_FAVORITE_LINKEDIN_PROFILES",
	SUCCEEDED_ALL_FAVORITE_LINKEDIN_PROFILES:"SUCCEEDED_ALL_FAVORITE_LINKEDIN_PROFILES",

	REQUESTED_FAVORITE_LINKEDIN_PROFILES:"REQUESTED_FAVORITE_LINKEDIN_PROFILES",
	FAILED_FAVORITE_LINKEDIN_PROFILES:"FAILED_FAVORITE_LINKEDIN_PROFILES",
	SUCCEEDED_FAVORITE_LINKEDIN_PROFILES:"SUCCEEDED_FAVORITE_LINKEDIN_PROFILES",
	//COMPANIES
	REQUESTED_FAVORITE_COMPANIES:"REQUESTED_FAVORITE_COMPANIES",
	FAILED_FAVORITE_COMPANIES:"FAILED_FAVORITE_COMPANIES",
	SUCCEEDED_FAVORITE_COMPANIES:"SUCCEEDED_FAVORITE_COMPANIES",
};