export default {
	// GITHUB PROFILES
	REQUESTED_ALL_GITHUB_PROFILES: "REQUESTED_ALL_GITHUB_PROFILES",
	SUCCEEDED_ALL_GITHUB_PROFILES: "SUCCEEDED_ALL_GITHUB_PROFILES",
	FAILED_ALL_GITHUB_PROFILES: "FAILED_ALL_GITHUB_PROFILES",

	REQUESTED_FAVORITE_GITHUB_PROFILES: "REQUESTED_FAVORITE_GITHUB_PROFILES",
	SUCCEEDED_FAVORITE_GITHUB_PROFILES: "SUCCEEDED_FAVORITE_GITHUB_PROFILES",
	FAILED_FAVORITE_GITHUB_PROFILES: "FAILED_FAVORITE_GITHUB_PROFILES",

	REQUESTED_GITHUB_PROFILES_BY_PAGE: "REQUESTED_GITHUB_PROFILES_BY_PAGE",
	SUCCEEDED_GITHUB_PROFILES_BY_PAGE: "SUCCEEDED_GITHUB_PROFILES_BY_PAGE",
	FAILED_GITHUB_PROFILES_BY_PAGE: "FAILED_GITHUB_PROFILES_BY_PAGE",

	// LINKEDIN PROFILES
	REQUESTED_ALL_LINKEDIN_PROFILES:"REQUESTED_ALL_LINKEDIN_PROFILES",
	FAILED_ALL_LINKEDIN_PROFILES:"FAILED_ALL_LINKEDIN_PROFILES",
	SUCCEEDED_ALL_LINKEDIN_PROFILES:"SUCCEEDED_ALL_LINKEDIN_PROFILES",


	REQUESTED_LINKEDIN_PROFILES_BY_PAGE: "REQUESTED_GITHUB_PROFILES_BY_PAGE",
	SUCCEEDED_LINKEDIN_PROFILES_BY_PAGE: "SUCCEEDED_GITHUB_PROFILES_BY_PAGE",
	FAILED_LINKEDIN_PROFILES_BY_PAGE: "FAILED_GITHUB_PROFILES_BY_PAGE",

	REQUESTED_FAVORITE_LINKEDIN_PROFILES:"REQUESTED_FAVORITE_LINKEDIN_PROFILES",
	FAILED_FAVORITE_LINKEDIN_PROFILES:"FAILED_FAVORITE_LINKEDIN_PROFILES",
	SUCCEEDED_FAVORITE_LINKEDIN_PROFILES:"SUCCEEDED_FAVORITE_LINKEDIN_PROFILES",

	//COMPANIES
	REQUESTED_FAVORITE_COMPANIES:"REQUESTED_FAVORITE_COMPANIES",
	FAILED_FAVORITE_COMPANIES:"FAILED_FAVORITE_COMPANIES",
	SUCCEEDED_FAVORITE_COMPANIES:"SUCCEEDED_FAVORITE_COMPANIES",

	REQUESTED_COMPANIES_BY_PAGE:"REQUESTED_COMPANIES_BY_PAGE",
	FAILED_COMPANIES_BY_PAGE:"FAILED_COMPANIES_BY_PAGE",
	SUCCEEDED_COMPANIES_BY_PAGE:"SUCCEEDED_COMPANIES_BY_PAGE",

	//JOBS
	REQUESTED_JOBS_BY_PAGE: "REQUESTED_JOBS_BY_PAGE",
	SUCCEEDED_JOBS_BY_PAGE: "SUCCEEDED_JOBS_BY_PAGE",
	FAILED_JOBS_BY_PAGE: "FAILED_JOBS_BY_PAGE",


};