export default {
	// GITHUB PROFILES
	REQUESTED_ALL_GITHUB_PROFILES: "REQUESTED_ALL_GITHUB_PROFILES",
	SUCCEEDED_ALL_GITHUB_PROFILES: "SUCCEEDED_ALL_GITHUB_PROFILES",
	FAILED_ALL_GITHUB_PROFILES: "FAILED_ALL_GITHUB_PROFILES",
};